# Generated by Django 3.1.14 on 2022-05-03 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('run_at', models.DateTimeField()),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('type_key', models.CharField(max_length=15)),
                ('status', models.CharField(choices=[('new', 'New'), ('running', 'Processing'), ('done', 'Completed'), ('failed', 'Failed'), ('retry', 'Retry')], default='new', max_length=15)),
                ('fail_reason', models.CharField(blank=True, max_length=250, null=True)),
                ('times_executed', models.SmallIntegerField(default=0)),
                ('_metadata', models.TextField(max_length=512)),
            ],
        ),
    ]
